name: Deploy Latest WSTG Json Checklist

on:
  push:
    branches:
      - master
    paths:
      - 'document/**'

jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install moreutils
    - name: Git Setup Global Config
      run: |
        # Git setup
        export GITHUB_USER=wstgbot
        echo "GITHUB_USER=$GITHUB_USER" >> $GITHUB_ENV
        git config --global user.email "62450690+wstgbot@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
    - name: Setup Environment Variables
      run : |
        # Setup some env vars etc for future use
        echo "SRC_BASE="OWASP/wstg@"$(git log -1 --format=format:%h)" >> $GITHUB_ENV
        echo "BRANCH_STAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
        echo "SHORT_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
    - name: Create Feature Branch
      run: |
        # Checkout what will be the new feature branch
        git checkout -b $BRANCH_STAMP
    - name: Run Json Build
      run: npm run-script jsongen

    - name: Push Feature Branch and Raise PR
      run: |
        git remote set-url origin https://$GITHUB_USER:${{ secrets.wstg_deploy_token }}@github.com/rejahrehim/wstg.git
        git add checklist/Testing-checklist.json
        git commit -m "Publish Latest Json checklist $SHORT_DATE" -m "Updates based on $SRC_BASE"
        git push --set-upstream origin $BRANCH_STAMP
        hub pull-request --no-edit
